[platformio]
default_envs = heltec_v4_bootstrap
description = lora20 bootstrap firmware for Heltec V4 over USB serial

[env:heltec_v4_bootstrap]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
lib_ldf_mode = chain+
build_flags =
  -std=gnu++17
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM
  -D REGION_EU868
  -D MCU_ESP32_S3
  -D HELTEC_BOARD=30
  -D SLOW_CLK_TPYE=0
  -D WIFI_LORA_32_V4
  -D RADIO_CHIP_SX1262
  -D LoRaWAN_DEBUG_LEVEL=0
  -D ACTIVE_REGION=LORAMAC_REGION_EU868
  -D LORAWAN_PREAMBLE_LENGTH=8
  -D LORAWAN_DEVEUI_AUTO=0
  -D LORA_RX_LNA=1
  -D GPIO_PIN_COUNT=SOC_GPIO_PIN_COUNT
  -D USE_KCT8103L_PA
  -D Vext=36
  -D LED=35
  -D RST_OLED=21
  -D SCL_OLED=18
  -D SDA_OLED=17
  -D RST_LoRa=12
  -D BUSY_LoRa=13
  -D DIO0=14
  -D LORA20_BATTERY_PIN=1
  -D LORA20_BATTERY_ENABLE_PIN=37
  -D LORA20_BATTERY_DIVIDER=4.9f
  -D LORA20_BATTERY_MIN_V=3.2f
  -D LORA20_BATTERY_MAX_V=4.2f
  -D LORA20_FW_VERSION=\"0.1.3-bootstrap-r13\"
  -L"$PROJECT_LIBDEPS_DIR/$PIOENV/Heltec ESP32 Dev-Boards/src/esp32s3"
  -llorawan
lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  https://github.com/orlp/ed25519.git
  C:/Users/Kosmo/Documents/Playground/_vendor/Heltec_ESP32
  adafruit/Adafruit GFX Library @ ^1.11.11
  adafruit/Adafruit BusIO @ ^1.16.1
